import { test, expect } from '@playwright/test';
import fs from 'fs';

/**
 * API-LEVEL TEST — GitHub Issue #20
 * https://github.com/Gayand-soul/playwright-qa-automation-portfolio/issues/20
 *
 * What this proves vs. what it doesn't:
 * This test POSTs a hardcoded payload — including cooking_time_minutes: 30.075,
 * the exact value captured from the real bug — straight to the Supabase REST
 * API, bypassing the frontend entirely. It proves Postgres correctly rejects
 * a non-integer value for the `cooking_time_minutes` integer column (a stable,
 * valuable schema-level check). It does NOT prove the frontend still produces
 * a float — since we're injecting 30.075 ourselves, this test will return the
 * same 400 forever, even after the frontend bug is fixed.
 *
 * We tried to reproduce this end-to-end through the UI first (real mic input,
 * see creator-recipe-publish.spec.ts) and confirmed it isn't reliably
 * automatable: Playwright's fake microphone feeds silence, which the app
 * turns into an empty/generic recipe that saves fine (201), and the app's
 * save flow has since become two steps (draft creation via a transcription
 * Edge Function, then a separate PATCH to publish) rather than the single
 * atomic POST originally captured. So this API-level test and the UI-level
 * error-banner test are complementary, not redundant — keep both:
 *   - this test: guards the backend schema constraint directly
 *   - creator-recipe-publish.spec.ts: guards the frontend's handling of that
 *     error, regardless of how the bad value gets produced
 *
 * Auth: reuses the same pattern as supabase-api.spec.ts — the creator's
 * access token is read from playwright/.auth/creator.json (gitignored,
 * regenerated by auth-setup.spec.ts), not hardcoded. The anon key is a
 * Supabase publishable key, safe to keep in source alongside the URL.
 */

const SUPABASE_URL = 'https://fejqqtatmdvqefwizhlx.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_7WL4nUO6L6HqGQThFKm3Lw_Vrui6PQv';

function getAccessToken(storageStatePath: string): string {
  const state = JSON.parse(fs.readFileSync(storageStatePath, 'utf-8'));
  const origin = state.origins.find((o: any) => o.origin.includes('lovable.app'));
  const entry = origin.localStorage.find(
    (item: any) => item.name.startsWith('sb-') && item.name.endsWith('-auth-token')
  );
  return JSON.parse(entry.value).access_token;
}

test('rejects a recipe with a non-integer cooking_time_minutes — issue #20', async ({ request }) => {
  const token = getAccessToken('playwright/.auth/creator.json');

  // Payload matches the real capture from Issue #20 (minus image_url, which
  // pointed at a since-expired uploaded photo and isn't required to trigger
  // the schema error).
  const payload = {
    title: 'Playwright API Test — safe to delete',
    cooking_time_minutes: 30.075,
    description: '',
    ingredients: [{ name: 'bacon' }],
    is_published: true,
    steps: [{ instruction: 'Ta fram baconet ur förpackningen.', kind: 'prep', duration_seconds: 6 }],
    transcript: 'Playwright API-level test payload — see Issue #20.',
  };

  const response = await request.post(`${SUPABASE_URL}/rest/v1/recipes`, {
    headers: {
      apikey: SUPABASE_ANON_KEY,
      Authorization: `Bearer ${token}`,
      // Ask PostgREST to return the created row if the insert unexpectedly
      // succeeds, so we can clean it up below.
      Prefer: 'return=representation',
    },
    data: payload,
  });

  const body = await response.json();

  // Safety net: if this ever unexpectedly succeeds (e.g. someone fixes the
  // bug by widening the column instead of rounding client-side), don't leave
  // junk rows in the sandbox DB — delete what we just created and fail loudly
  // so it's obvious this test needs to be revisited.
  if (response.status() === 201) {
    const createdId = Array.isArray(body) ? body[0]?.id : body?.id;
    if (createdId) {
      await request.delete(`${SUPABASE_URL}/rest/v1/recipes?id=eq.${createdId}`, {
        headers: {
          apikey: SUPABASE_ANON_KEY,
          Authorization: `Bearer ${token}`,
        },
      });
    }
    throw new Error(
      `Expected 400/22P02 for a non-integer cooking_time_minutes, but insert succeeded (id: ${createdId}). ` +
      `The row was deleted. This likely means the column type changed (e.g. to numeric) — update or remove this test.`
    );
  }

  expect(response.status()).toBe(400);
  expect(body.code).toBe('22P02');
  expect(body.message).toContain('invalid input syntax for type integer');
});